[package]
name = "wfc"
description = "Generate images using Wave Function Collapse"
version = "0.8.1"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/wfc.git"
repository = "https://github.com/stevebob/wfc.git"
documentation = "https://docs.rs/wfc"


[dependencies]
rand = "0.7"
hashbrown = "0.1"
coord_2d = "0.2"
grid_2d = "0.12"
direction = "0.17"

